### ISSUE TITLE
Today lesson 11/04/2021 not shared to us

### ISSUE THREAD

**Issue by eugenelim218** [dheeraj-thedev/FullStackDevelopment#3]
Dear sir,

I need to inform you that the 4 Javascript codes for today lesson was not shared to us successfully in GitHub. I just login to my GitHub to download the codes, but surprisingly all the codes covered today not shared to us, they are still yesterday codes. Kindly can you share the codes here, or send the codes to my email at myfreedom218@gmail.com. Pls i need to revise now ok. 

Thank you sir.

Regards,
Eugene

**Comment by shik28tech** [comment]
Dear sir,

The same issue is for me also sir the codes that you wrote on the same file along with the arrays one hasn't been shared to us. Can you kindly address this issue and upload it on github. Please do the needful.

Thank you sir.

Regards,
Shikhar

**Comment by dheeraj-thedev** [comment]
Hi I have added all the files please do let me know if any issues are there
