### ISSUE TITLE
17 April Lesson not shared to us

### ISSUE THREAD

**Issue by eugenelim218** [dheeraj-thedev/FullStackDevelopment#4]
Sir i don't trust u sharing to GitHub anymore, is very mentally tiring having to check our GitHub to ensure that u have successfully committed and push the code for that day lesson to us. GitHub has many problem. I don't trust GitHub anymore ok... Kindly pls zip your code for the day lesson and send to my email address, pls do that ok.

My email : myfreedom218@gmail.com

Pls do that from tomorrow onwards, thank you very much. 

Only to me ok. Thank you.

**Comment by dheeraj-thedev** [comment]
I will share it on mail
